/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRecipeRouteImport } from './routes/newRecipe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthRouteImport } from './routes/api/auth'

const NewRecipeRoute = NewRecipeRouteImport.update({
  id: '/newRecipe',
  path: '/newRecipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newRecipe': typeof NewRecipeRoute
  '/api/auth': typeof ApiAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newRecipe': typeof NewRecipeRoute
  '/api/auth': typeof ApiAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newRecipe': typeof NewRecipeRoute
  '/api/auth': typeof ApiAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/newRecipe' | '/api/auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newRecipe' | '/api/auth'
  id: '__root__' | '/' | '/newRecipe' | '/api/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRecipeRoute: typeof NewRecipeRoute
  ApiAuthRoute: typeof ApiAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newRecipe': {
      id: '/newRecipe'
      path: '/newRecipe'
      fullPath: '/newRecipe'
      preLoaderRoute: typeof NewRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRecipeRoute: NewRecipeRoute,
  ApiAuthRoute: ApiAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
